<?php
/**
 * @file header.tpl.inc
 * Implementation to display the footer region.
 */
?>

<a class="sr-only sr-only-focusable" href="#content" title="Skip to content">Skip to content
</a>
<header id="masthead-webapp" class="webapp-site-header" role="banner">
  <h3 class="killer-logo">
    <a href="http://www.utk.edu">The University of Tennessee, Knoxville
    </a>
  </h3>
  <h2 class="sr-only">
    <a href="https://www.lib.utk.edu" rel="home">University Libraries
    </a>
  </h2>
  <div id="sitetitle-webapp">
    <h2 class="department">
      <a href="/" title="Tennessee Research and Creative Exchange" rel="home">TRACE: Tennessee Research and Creative Exchange
      </a>
      <small>
        <a href="https://www.lib.utk.edu">University Libraries
        </a>
      </small>
    </h2>
  </div>
</header>
